### PR TITLE
Create consumer from client, and exposing cluster configuration

### PR DESCRIPTION
**Pull request by adzr**
Adding the ability to create cluster consumer from an already active client, and adding a function to expose cluster configuration to be able to take decisions based on cluster configuration settings like whether to read from notifications channel or not.

### CODE REVIEW

**Comment by dim** [comment]
@adzr thanks but could you please explain why this is useful to you? I have only recently removed this feature in https://github.com/bsm/sarama-cluster/commit/748fdb134cad531086c5a8995b3dd86dbbf3189c as it just doesn't work - you cannot share the same client between multiple consumer groups. Here's the corresponding sarama ticket: https://github.com/Shopify/sarama/issues/958

**Comment by crast** [comment]
@dim based on above justification, I'd say kill NewClient then too, since Client is of minimal use right now, and mark a 3.x version tag since removing that API was a semver-breaking change

**Comment by adzr** [comment]
@dim I'm facing a scenario where message consumption needs to be paused/resumed frequently, I thought that closing/recreating the consumer may be more efficient than recreating the whole client keeping the "1 client 1 consumer" pattern.

**Comment by dim** [comment]
@adzr that makes sense. @crast instead of killing `NewClient`, I might actually just add some documentation to indicate that clients must not be shared between goroutines. Thoughts?

**Comment by adzr** [comment]
@dim Yea, I think this will be fine for now, I'll make sure to share any thoughts pop into my head.

**Comment by crast** [comment]
@dim with a Client you can't currently create a consumer, since there's no `NewConsumerFromClient`

Basically, since users outside the package can't get access to turning a client into a consumer anymore... a public `NewClient` doesn't have much purpose

**Comment by dim** [comment]
@crast the purpose of this PR is to bring `NewConsumerFromClient` back :)

**Comment by adzr** [comment]
@dim Have you had a final decision on this yet?

**Comment by dim** [comment]
@adzr sorry, busy week(s), will take a look tomorrow

**Comment by dim** [comment]
@adzr @crast could you please take a look at #182. It should fix this issue once and for all

**Pull request closed without merging**
