### PR TITLE
Separate out the partitions into separate consumers.

### PR DESCRIPTION
**Pull request by crast**
I know this looks like a repeat of #147 but I figured I'd add my approach here as a competing approach - I should mention this code has been in use in production at my organization processing billions of messages a week for [well over a year now](https://github.com/crast/sarama-cluster/commit/47bb78316eabb872122acb6fd402e4d5622c0cf6), all I did was rebase it and clean up docs.

(Also worth mentioning, this doesn't break the existing API compatibility, just adds a new method which is enabled by a configuration option)

----

The criteria for this system:

1) Give something which looks like a sarama.PartitionConsumer to allow
portability for existing code to use sarama-cluster with minimal
shimming.

2) Gracefully handle rebalances of partitions / discovering more
partitions by yielding the partitions on a channel as they are
found/added.

3) Maintain a go-like pattern; let the user of the library decide what
to do with each partition, with regards to concurrency, etc... we
don't run goroutines for them, and don't force them to respond to
callbacks on an unknown goroutine.

### CODE REVIEW

**Comment by crast** [comment]
Addendum: a rationale for _why_ this is needed:
At my organization,  We're using Kafka effectively as a distributed ordered 'binary log' [following the patterns outlined here](https://engineering.linkedin.com/distributed-systems/log-what-every-software-engineer-should-know-about-real-time-datas-unifying). Naturally, if the binary log is used to serialize writes out to the database, we don't commit kafka offsets until that happens.

We have a lot of partitions on some topics, and often we partition by user ID, as that's a sensible partition key for the properties of our actual handling of work (cache locality, writing the user's events in-order, etc). In other words, we have a workload large enough (some of them with 50+ partitions and often 10+ workers) that sarama-cluster is obviously needed and important.

One could presumedley simply take the existing `Messages()` output and fan that out to more channels based on any criteria we want, but this creates a problem:  We might have a period of time where we end up with a semi-hot partition, maybe due to a DDOS, maybe someone is importing a lot of personal data, etc.  During that time, we actually are _okay_ with a partition falling behind the others being consumed with the host. However, in that scenario, we'd run into a limit as one of our secondary channels would eventually get filled, and other channels would stop getting data while we block filling the busiest channel.  This could be mitigated by increasing the depth of all these fanout channels, but at the cost of increasing the memory usage of our workers during these times.

So while we already _do_ fan things out, for various reasons, including tracking offsets and commits, this problem is much easier to reason about when we have each partition separated out, not backlogging writes into a single channel bottleneck.

**Comment by gwik** [comment]
I'am the author of #147 and I don't won't to fight on which one gets merge. I'd just like one of them to be.
The rational is very simple IMO, sometimes you need to run blocking code inside the `Messages()` channel receiver loop and you don't want to block on all the partitions.
The most common real world example to me is you buffer messages or computations related to messages on a partition basis and you want to flush, then commit offsets.
This is true for database transactions, temporary files (I do this pretty often with GCS).
The second usage I have, maybe it is not so common is I need to load some state for db, files, whatever before processing a partition. If a rebalance happen and I get a new (or probably several new partitions) I don't want to block the other partition handlers/controllers/whatever you wanna call it from being processed.

I like this implementation as it exposes familiar sarama.Consumer interface, maybe mine is more lightweight. As I said I don't care which one gets merged, please just merge one!

Of course there are ways to workaround it, but it seems so natural to use the partition consumers that already exists, already runs in a separate isolated environment (goroutine) instead of merging all the state in to one and having to use dubious strategies (in term of software design and concurrency) to split them back.

@dim, would you please consider it ?

**Comment by dim** [comment]
Hey, my apologies, it's been a busy few weeks for us. Will take a look later this week.

**Comment by gwik** [comment]
> Hey, my apologies, it's been a busy few weeks for us. Will take a look later this week.
I understand we're all busy, just wanted to bump this, thank you.

**Comment by dim** [comment]
@crast thanks for the explanation, your use case and stratego both sound very familiar :) We are also processing ~1M events every second and had - so far - no problems with channel congestion, but more in this later. 

So that I understand: you iterate over `Partitions()` and spawn a new goroutine for each received `PartitionConsumer`. In those goroutines you then subscribe to the individual `Messages()` channels to consume the partitions. On rebalance the `Messages` channel is closed and you get a new set of `PartitionConsumer` instances pushed into `Partitions()`. 

This is an elegant solution and I am happy to merge it, but I still would like to understand what advantage you get compared to spawning more consumer instances. Assuming you have a topic with 64 partitions and you spawn two workers (processes), each with 32 consumer instances, something like the below. This would result in one partition per topic and give you exactly what you are suggesting or am I missing something?

```
func main() {
  client, _ := cluster.NewClient([]string{"127.0.0.1:9092"}, nil)
  for i := 0; i < 32; i++ {
    go consume(client)
  }
}

func consume(client *cluster.Client) {
  consumer, _ := cluster.NewConsumerFromClient(client, "my-group", []string{"my-topic"})
  defer consumer.Close()

  for m := range consumer.Messages() {
    // do stuff here
  }
}
```

**Comment by crast** [comment]
@dim That makes sense, but then you need secondary coordination (another datastore or something like zookeeper/consul to manage locks or metadata) to know how many instances of `Client` to spawn up, varying based on how many other machines/processes are running (which in an autoscaling world, could get interesting) and how many partitions exist in the cluster.

Furthermore in your example, say 8 of the 32 partitions are on a single broker, that solution will make 8 TCP connections to each broker Meanwhile the standard single-client version, in the way sarama works, [will make fetch requests to multiple partitions](https://github.com/Shopify/sarama/blob/c7650177c9f7b51aa9410e270adcbc2b16c16b9e/consumer.go#L556) with a single broker connection, requesting more data for partition N as long as the channel for that partition has room (and [will stop requesting more data for that partition for a while](https://github.com/Shopify/sarama/blob/c7650177c9f7b51aa9410e270adcbc2b16c16b9e/consumer.go#L682-L685) until that `messages` channel has room again) All this smarts built into Sarama to more efficiently fill queues and multiplex work in a single broker connection are somewhat thwarted by running tons of clients.. mostly at the cost of higher resource use on the kafka broker.

**Comment by crast** [comment]
> So that I understand: you iterate over Partitions() and spawn a new goroutine for each received PartitionConsumer. In those goroutines you then subscribe to the individual Messages() channels to consume the partitions. On rebalance the Messages channel is closed and you get a new set of PartitionConsumer instances pushed into Partitions().

yeah, it'd look something like this:
https://gist.github.com/crast/c8570e63657f4d743319230f1f87f55e

(I also included an implementation of the "ack tracking" algorithm we came up with for out-of-order acks.

**Comment by dim** [comment]
@crast 

> Meanwhile the standard single-client version, in the way sarama works, will make fetch requests to multiple partitions with a single broker connection ...

If you call `cluster.NewConsumerFromClient` as I did in my example, all connections will go through a single client, exactly like in your version.

> ... then you need secondary coordination (another datastore or something like zookeeper/consul to manage locks or metadata) to know how many instances of Client to spawn up, varying based on how many other machines/processes are running ...

I really don't think you do. Assuming you (roughly) know the number of your partitions is N, just start N consumer instances per worker. With two workers, half of your consumers/goroutines would be idle, but given that they are all wired through a single `Client` the overhead is absolutely minimal. 

Again, I am not totally opposed to your PR, but I think it adds an unnecessary level of complexity to many users, so I am trying to get a sense of where my outlined approach would be inadequate.

**Comment by crast** [comment]
@dim ah, I didn't notice that distinction.
Yes, it seems like it'd use the same overall client/broker connections and multiplex sensibly.

I understand not wanting to further complicate the API... I'd have to try it to see how it turns out in production for us. I suspect it will work reasonably, though.  Re-reading `cluster/consumer.go` I *think* what's going to happen in your example is the same process is going to attempt join the group 32x and hold leader elections with itself, so there's a bit more 'thrashing' when re-elections happen with so many more group members, but once it "settles" it should end up not costing much, other than a bunch of extra goroutines running the mainLoop, topic watcher loop, and heartbeat loop.

**Comment by dim** [comment]
@crast I would really appreciate if you could some side-by-side testing and post your results. Despite the similarities, I am sure your use-case/process is ever so slightly different from ours. 

We would like sarama-cluster to address a broad set of needs, hence it would be really great to see if the proposed approach is equally applicable to your domain.

**Comment by crast** [comment]
@dim I'm having trouble getting multiple consumers to start attached to a single `cluster.Client` instance, based on your example idea.  My guess is that this is not actually possible to do.

At first I thought it was issues with our internal libraries that wrap sarama-cluster, so in investigating it eventually I pulled all the code out to the smallest _realistic simulated work_ example I could, to eliminate variables.

And what I found was that when you start more than a single `Consumer` then you start getting a mass of disconnection errors.
Eventually, all of the consumers but one die off and one of them may proceed, but not otherwise.
So it looks something like:

```
$ export NUM_CONSUMERS=2
$ ./consumer-multi-example 
2017/09/26 00:11:11 Going to start 2 consumers
2017/09/26 00:11:41 Consumer 0 ERR: read tcp 172.30.8.224:45714->172.30.8.120:9092: i/o timeout
2017/09/26 00:11:41 Consumer 1 ERR: read tcp 172.30.8.224:45714->172.30.8.120:9092: i/o timeout
2017/09/26 00:11:41 Consumer 0 ERR: read tcp 172.30.8.224:45714->172.30.8.120:9092: i/o timeout
2017/09/26 00:12:11 Consumer 0 ERR: kafka server: The provided member is not known in the current generation.
```

So I made an even simpler client example minus my offset commit code, attached as simplest-consumer.go, to prove out it was solely the consumer itself, and it did show that, with identical output to above.

See gist with all the files and instructions: https://gist.github.com/crast/659d602c77e4c0b90b3cb9b8d2784ef4

What I _think_ is happening is that they are conflicting over access to the broker, or maybe even over access to multiple group joins, which the kafka cluster doesn't like, and eventually kicks the client off, and eventually sarama makes new broker connections for the "non-broken" remaining client ID.

**Comment by dim** [comment]
@crast you are right, it's actually impossible (at the moment) to use the same client across multiple consumers. This is actually a bug, let me raise this with sarama.

**Comment by dim** [comment]
@crast here's some feedback from sarama - https://github.com/Shopify/sarama/issues/958#issuecomment-332196960

There are a few things I/we could do:

1. I could remove `NewConsumerFromClient` (which doesn't seem to be used as no one has ever mentioned to me that it's not working) and merge your PR
2. I could create a new `Broker` connection on rebalance to join & sync groups

I am also (still, sorry) tempted to just remove `NewConsumerFromClient`. Your PR is reasonable, but all it does is a classic "fan-out", something you could equally achieve through something as simple as https://stackoverflow.com/a/16931348. You could argue that there would be additional multiplex/fan-out overhead, but I don't believe it is really significant. Thoughts?

**Comment by crast** [comment]
> Your PR is reasonable, but all it does is a classic "fan-out", something you could equally achieve through something as simple as https://stackoverflow.com/a/16931348. You could argue that there would be additional multiplex/fan-out overhead, but I don't believe it is really significant. Thoughts?

@dim That doesn't actually solve the problem... fanning out after the implicit "fanning in" of sarama-cluster means that the longest queued partition will cause the shared "party line" channel to slow down other partitions from proceeding... you can mitigate it with increased channel depth on the fan-out channels, but then you pay for it in memory usage... at some point you are going to run into the same problem regardless.

The net effect is increased "time to be seen" latency for the messages on partitions which are closer to "real time"

Here's a physical analogy:  say you had a 5-lane highway, and normally, they all proceed at speed. But today, there's the big championship football game, and therefore the right-most lane is the "slow lane" since everyone's queueing to the exit that will go to the football game.  Normally, people in the left four lanes can proceed at their normal speed, while people waiting for the football game are queued up in the right-most line.

But now, you add a construction zone a mile prior to the football exit, where everyone merges into a single lane, before going into the restriction.. Even if near the end of the single lane, everyone starts speeding up, and afterwards, they fan back out into their respective lanes (with football fans going back to the right-most lane to get towards their exit),  there's no way in that scenario to say that people who were trying to avoid the football traffic are not negatively affected in their arrival time, simply due to the fact that the long queue on the right lane is effectively extended into the single lane restriction.

**Comment by dim** [comment]
@crast makes sense, could you please take a look at #173 which uses most of your solution but adds tests :)

**Comment by dim** [comment]
closing in favour of #173

**Comment by chandradeepak** [comment]
I tried NewConsumerFromClient when i was first started sarama-cluster it never worked. so we used NewConsumer for all our subscribers.  Just saying it is right to remove that .

**Pull request closed without merging**
