### PR TITLE
Make Close thread-safe

### PR DESCRIPTION
**Pull request by dim**
Fixes #183

### CODE REVIEW

**Comment by varun06** [comment]
👍

**Comment by timoha** [comment]
There’s a bit of different semantic here. When the Close function is called second time, it will return right away, without waiting for the first Close() call completion. That could lead to some race conditions in case your program needs to make sure that Close() actually finished before proceding (like exiting the process).

**Comment by timoha** [comment]
imho, you should either use sync.Once #183 or a sync.Mutex.

**Comment by dim** [comment]
OK, fine with me, updated!

**Pull request merged**
