### PR TITLE
Make message channel buffered

### PR DESCRIPTION
**Pull request by Mirey**
Change the messages channel to be, `client.config.ChannelBufferSize` big, rather than unbuffered.

### CODE REVIEW

**Comment by dim** [comment]
Sorry, I will have to decling. This is something that we had in the past but it causes massive races. As buffered messages must be processed in `MaxProcessingTime` in order to be consumed uniquely. 

If you are worried about performance, I have done extensive benchmarks on this one too and adding a buffer has virtually no benefit as the underlying channels are already buffered.

**Comment by Mirey** [comment]
Ah, makes sense. I looked around a little bit and couldn't see any tickets about it.
Thanks for the quick response.

**Comment by AlmogBaku** [comment]
@dim What should I do in case I process the messages in parallel? should I limit the goroutines?:
```for {
    msg, ok := <-consumer.Messages()
    if ok {
        go someProcessing(msg)
    }
}```

**Comment by dim** [comment]
@AlmogBaku pls take a look at https://github.com/Shopify/sarama/pull/1099, this will solve the problem of parallelism

**Pull request closed without merging**
