### PR TITLE
V3

### PR DESCRIPTION
**Pull request by dim**

### CODE REVIEW

**Comment by steve-gray** [comment]
@dim - What's the current status and timeline on this - are there open areas for PR/contributions?

I'm encountering issues with shutdown race conditions inside the sarama-cluster Close methods, and the other issue report indicated it won't be fixed in the as-is code pending this rewrite?

**Comment by dim** [comment]
@steve-gray sorry was travelling, I will resume work on the https://github.com/Shopify/sarama/pull/1099 PR this week

**Comment by steve-gray** [comment]
@dim - No worries - if there's anything to help with, I'm reasonably open to throwing time at it. In the meantime, I've mitigated the shutdown lockups/memory leaks with a drain routine I call in a goroutine immediately before stopping the consumer, forcing it to drain out completely - probably need something like this in the mainline - as I can't imagine there's a use case for Stop() that isn't going to need to deal with this manually:

````
func drainConsumer(c *cluster.Consumer) {
	if c == nil {
		return
	}

	// Errors
	go func() {
		for range c.Errors() {
		}
	}()

	// Notifications
	go func() {
		for range c.Notifications() {
		}
	}()

	// Messages
	go func() {
		for range c.Messages() {
		}
	}()

	// Partitions
	go func() {
		for p := range c.Partitions() {
			errClose := p.Close()
			log.WithError(errClose).Warn("kafka_draining_partition_aquired")
		}
	}()
}
````

**Comment by dim** [comment]
Closing in favour of #256

**Pull request closed without merging**
